add google tag manager
OpenBCI/Documentation pull request #202
Opened 2023-10-31 21:54 UTC by Andrey1994

2023-11-01 01:27 UTC, retiutut requested changes

2023-11-01 01:27 UTC, retiutut commented on website/docusaurus.config.js
>          "gtag": {
We should also remove gtag as part of this change.

2023-11-01 22:11 UTC, retiutut commented
But we likely need the google tag manager plugin.

2023-11-01 22:19 UTC, Andrey1994 commented
why

2023-11-02 17:19 UTC, retiutut commented
Gtag is the old analytics Gtm is the new one.

2023-11-02 17:24 UTC, Andrey1994 commented
And you've said to remove old one, so I did exactly that

2023-11-12 21:36 UTC, Andrey1994 commented on website/package.json
> +    "@docusaurus/plugin-google-tag-manager": "^2.4.3",
If you use the preset @docusaurus/preset-classic, you don't need to install this plugin as a dependency.

You can configure this plugin through the preset options. 

from docusaurus docs https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-google-tag-manager and its exactly the case here

2023-11-13 20:05 UTC, retiutut approved these changes

2023-11-13 20:06 UTC, merged