Dev motor imagery
OpenBCI/Documentation pull request #90
Opened 2021-12-15 22:57 UTC by devyansh

Motor Imagery Tutorial Documentation Updated

2021-12-16 00:44 UTC, evaesteban approved these changes

2021-12-16 23:32 UTC, retiutut requested changes
@devyansh Can you merge upstream/master into this branch?

2021-12-16 23:36 UTC, devyansh commented
I can look into this tomorrow

On Thu, Dec 16, 2021 at 6:33 PM Richard Waltman ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> @devyansh <https://github.com/devyansh> Can you merge upstream/master
> into this branch?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/OpenBCI/Documentation/pull/90#pullrequestreview-834701373>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AI2ODHZS2IHBSMNDGW3Y6F3URJZKVANCNFSM5KE26NBQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2021-12-17 17:42 UTC, devyansh commented
@retiutut I don't have write access. Can you give me the required access?

2021-12-17 19:02 UTC, retiutut approved these changes

2021-12-17 19:03 UTC, merged